/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package build_your_event;

import static build_your_event.BYE_REGISTER.tfbulan;
import static build_your_event.BYE_REGISTER.tfemail;
import static build_your_event.BYE_REGISTER.tfevent;
import static build_your_event.BYE_REGISTER.tfname;
import static build_your_event.BYE_REGISTER.tftahun;
import static build_your_event.BYE_REGISTER.tftanggal;
import static build_your_event.BYE_REGISTER.tftelp;
import javax.swing.ComboBoxModel;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author ASUS
 */
public class BYE_CUSTOM extends javax.swing.JFrame {

    /**
     * Creates new form BYE_OTHER
     */
    public BYE_CUSTOM() {
        initComponents();
        // mengambil ukuran layar
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        cbstage = new javax.swing.JComboBox();
        cbcultery = new javax.swing.JComboBox();
        cblighting = new javax.swing.JComboBox();
        cbsound = new javax.swing.JComboBox();
        cbinstrument = new javax.swing.JComboBox();
        tfstand = new javax.swing.JTextField();
        tftable = new javax.swing.JTextField();
        tfgenset = new javax.swing.JTextField();
        tfchair = new javax.swing.JTextField();
        btncutlery = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfprice = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbstand = new javax.swing.JCheckBox();
        cbtable = new javax.swing.JCheckBox();
        cbchair = new javax.swing.JCheckBox();
        cbgenset = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnlighting = new javax.swing.JButton();
        btnsound = new javax.swing.JButton();
        btninstrument = new javax.swing.JButton();
        btnprint = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        tfhargagenset = new javax.swing.JTextField();
        tfhargainstrument = new javax.swing.JTextField();
        tfhargasound = new javax.swing.JTextField();
        tfhargalighting = new javax.swing.JTextField();
        tfhargacutlery = new javax.swing.JTextField();
        tfhargachair = new javax.swing.JTextField();
        tfhargatable = new javax.swing.JTextField();
        tfhargastand = new javax.swing.JTextField();
        tfhargastage = new javax.swing.JTextField();
        btnhitung = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bye_music_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        cbstage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "1. SMALL (4x6 m2)", "2. MEDIUM (6x8 m2)", "3. LARGE (10x16 m2)", "4. EXTRALARGE (20x22 m2)", " " }));
        cbstage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbstageActionPerformed(evt);
            }
        });

        cbcultery.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "1. SMALL(200pcs)", "2. MEDIUM(500pcs)", "3. LARGE(800pcs)", "4. EXTRA LARGE(1200pcs)", " " }));
        cbcultery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbculteryActionPerformed(evt);
            }
        });

        cblighting.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "1. BASIC", "2. MEDIUM", "3. EXPERT", "4. EXCLUSIVE", " " }));
        cblighting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cblightingActionPerformed(evt);
            }
        });

        cbsound.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "1. BASIC", "2. MEDIUM", "3. EXPERT", " " }));
        cbsound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsoundActionPerformed(evt);
            }
        });

        cbinstrument.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "1. BASIC", "2.MEDIUM", "3.EXPERT", " " }));
        cbinstrument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbinstrumentActionPerformed(evt);
            }
        });

        tfstand.setBackground(new java.awt.Color(153, 153, 153));
        tfstand.setText("0");
        tfstand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfstandActionPerformed(evt);
            }
        });

        tftable.setBackground(new java.awt.Color(153, 153, 153));
        tftable.setText("0");
        tftable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftableActionPerformed(evt);
            }
        });

        tfgenset.setBackground(new java.awt.Color(153, 153, 153));
        tfgenset.setText("0");
        tfgenset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfgensetActionPerformed(evt);
            }
        });

        tfchair.setBackground(new java.awt.Color(153, 153, 153));
        tfchair.setText("0");
        tfchair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfchairActionPerformed(evt);
            }
        });

        btncutlery.setText("Info");
        btncutlery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncutleryActionPerformed(evt);
            }
        });

        tfprice.setBackground(new java.awt.Color(153, 153, 153));
        tfprice.setColumns(20);
        tfprice.setRows(5);
        jScrollPane1.setViewportView(tfprice);

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("X");

        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("X");

        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("X");

        cbstand.setText("STAND");
        cbstand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbstandActionPerformed(evt);
            }
        });

        cbtable.setText("TABLE");
        cbtable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtableActionPerformed(evt);
            }
        });

        cbchair.setText("CHAIR");
        cbchair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbchairActionPerformed(evt);
            }
        });

        cbgenset.setText("GENSET 700W");
        cbgenset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbgensetActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("STAGE");

        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("CUTLERY");

        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("LIGHTING");

        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("SOUND");

        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("INSTRUMENT");

        btnlighting.setText("Info");
        btnlighting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlightingActionPerformed(evt);
            }
        });

        btnsound.setText("Info");
        btnsound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsoundActionPerformed(evt);
            }
        });

        btninstrument.setText("Info");
        btninstrument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninstrumentActionPerformed(evt);
            }
        });

        btnprint.setText("Print");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Price :");

        tfhargagenset.setEditable(false);
        tfhargagenset.setText("0");
        tfhargagenset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhargagensetActionPerformed(evt);
            }
        });

        tfhargainstrument.setEditable(false);
        tfhargainstrument.setText("0");
        tfhargainstrument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhargainstrumentActionPerformed(evt);
            }
        });

        tfhargasound.setEditable(false);
        tfhargasound.setText("0");
        tfhargasound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhargasoundActionPerformed(evt);
            }
        });

        tfhargalighting.setEditable(false);
        tfhargalighting.setText("0");
        tfhargalighting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhargalightingActionPerformed(evt);
            }
        });

        tfhargacutlery.setEditable(false);
        tfhargacutlery.setText("0");
        tfhargacutlery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhargacutleryActionPerformed(evt);
            }
        });

        tfhargachair.setEditable(false);
        tfhargachair.setText("0");
        tfhargachair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhargachairActionPerformed(evt);
            }
        });

        tfhargatable.setEditable(false);
        tfhargatable.setText("0");
        tfhargatable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhargatableActionPerformed(evt);
            }
        });

        tfhargastand.setEditable(false);
        tfhargastand.setText("0");
        tfhargastand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhargastandActionPerformed(evt);
            }
        });

        tfhargastage.setEditable(false);
        tfhargastage.setText("0");
        tfhargastage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhargastageActionPerformed(evt);
            }
        });

        btnhitung.setText("HITUNG");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 51, 0));

        bye_music_label.setFont(new java.awt.Font("CaptainMarvel", 1, 24)); // NOI18N
        bye_music_label.setText("CUSTOM");

        jLabel2.setFont(new java.awt.Font("CaptainMarvel", 0, 11)); // NOI18N
        jLabel2.setText("CHOOSE WHAT YOU NEED");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bye_music_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bye_music_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbstand)
                                    .addComponent(cbtable)
                                    .addComponent(cbchair)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel15)
                                    .addComponent(cbgenset)
                                    .addComponent(jLabel1))
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(tfgenset, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbstage, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tfstand, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tftable, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tfchair, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(85, 85, 85))
                                            .addComponent(cbsound, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cblighting, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbcultery, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbinstrument, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btncutlery, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnlighting, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnsound, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btninstrument, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfhargalighting, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tfhargasound, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tfhargagenset, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tfhargacutlery, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(tfhargachair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(tfhargatable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfhargastand, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tfhargastage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfhargainstrument, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnprint)
                        .addGap(105, 105, 105)
                        .addComponent(btnhitung)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbstage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(tfhargastage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfstand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbstand)
                            .addComponent(tfhargastand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tftable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbtable)
                            .addComponent(tfhargatable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfchair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbchair)
                            .addComponent(tfhargachair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbcultery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncutlery)
                            .addComponent(jLabel15)
                            .addComponent(tfhargacutlery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cblighting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(btnlighting)
                            .addComponent(tfhargalighting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbsound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(btnsound)
                            .addComponent(tfhargasound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbinstrument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(btninstrument)
                            .addComponent(tfhargainstrument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfgenset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbgenset)
                            .addComponent(tfhargagenset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhitung)
                    .addComponent(btnprint)
                    .addComponent(btnBack))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new BYE_MENU().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void cbculteryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbculteryActionPerformed
        // TODO add your handling code here:
        int pilih;
        String ukuranCutlery;
        int hargaCutlery = 0;
        pilih = cbcultery.getSelectedIndex();
        switch (pilih)
        {
            case 1:
                ukuranCutlery = String.valueOf(cbcultery.getSelectedItem());
                hargaCutlery = 300000;
                break;
            case 2:
                ukuranCutlery = String.valueOf(cbcultery.getSelectedItem());
                hargaCutlery = 600000;
                break;
            case 3:
                ukuranCutlery = String.valueOf(cbcultery.getSelectedItem());
                hargaCutlery = 900000;
                break;
            case 4:
                ukuranCutlery = String.valueOf(cbcultery.getSelectedItem());
                hargaCutlery = 1300000;
                break;
        }
        tfhargacutlery.setText("" + hargaCutlery);
    }//GEN-LAST:event_cbculteryActionPerformed

    private void cblightingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cblightingActionPerformed
        // TODO add your handling code here:
        int pilih;
        String ukuranLighting;
        int hargaLighting = 0;
        pilih = cblighting.getSelectedIndex();
        switch (pilih)
        {
            case 1:
                ukuranLighting = String.valueOf(cblighting.getSelectedItem());
                hargaLighting = 1500000;
                break;
            case 2:
                ukuranLighting = String.valueOf(cblighting.getSelectedItem());
                hargaLighting = 3000000;
                break;
            case 3:
                ukuranLighting = String.valueOf(cblighting.getSelectedItem());
                hargaLighting = 5000000;
                break;
            case 4:
                ukuranLighting = String.valueOf(cblighting.getSelectedItem());
                hargaLighting = 7000000;
                break;
        }
        tfhargalighting.setText("" + hargaLighting);
    }//GEN-LAST:event_cblightingActionPerformed

    private void cbsoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsoundActionPerformed
        // TODO add your handling code here:
        int pilih;
        String ukuranSound;
        int hargaSound = 0;
        pilih = cbsound.getSelectedIndex();
        switch (pilih)
        {
            case 1:
                ukuranSound = String.valueOf(cbsound.getSelectedItem());
                hargaSound = 600000;
                break;
            case 2:
                ukuranSound = String.valueOf(cbsound.getSelectedItem());
                hargaSound = 1500000;
                break;
            case 3:
                ukuranSound = String.valueOf(cbsound.getSelectedItem());
                hargaSound = 2000000;
                break;
            case 4:
                ukuranSound = String.valueOf(cbsound.getSelectedItem());
                hargaSound = 7000000;
                break;
        }
        tfhargasound.setText("" + hargaSound);
    }//GEN-LAST:event_cbsoundActionPerformed

    private void cbinstrumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbinstrumentActionPerformed
        // TODO add your handling code here:
        int pilih;
        String ukuranInstrument;
        int hargaInstrument = 0;
        pilih = cbinstrument.getSelectedIndex();
        switch (pilih)
        {
            case 1:
                ukuranInstrument = String.valueOf(cbinstrument.getSelectedItem());
                hargaInstrument = 500000;
                break;
            case 2:
                ukuranInstrument = String.valueOf(cbinstrument.getSelectedItem());
                hargaInstrument = 1200000;
                break;
            case 3:
                ukuranInstrument = String.valueOf(cbinstrument.getSelectedItem());
                hargaInstrument = 2300000;
                break;
            case 4:
                ukuranInstrument = String.valueOf(cbinstrument.getSelectedItem());
                hargaInstrument = 7000000;
                break;
        }
        tfhargainstrument.setText("" + hargaInstrument);
    }//GEN-LAST:event_cbinstrumentActionPerformed

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
int h1,h2,h3,h4,h5,h6,h7,h8,h9,z1,z2,z3,z4,z5,z6,z7,z8;
h1 = Integer.valueOf(tfhargastage.getText());
h5 = Integer.valueOf(tfhargacutlery.getText());
h6 = Integer.valueOf(tfhargalighting.getText());
h7 = Integer.valueOf (tfhargasound.getText());
h8 = Integer.valueOf (tfhargainstrument.getText());
h9 = Integer.valueOf(tfhargagenset.getText());
z1 = Integer.valueOf(tfstand.getText());
z2 = Integer.valueOf(tfhargastand.getText());
z3 = Integer.valueOf(tftable.getText());
z4 = Integer.valueOf(tfhargatable.getText());
z5 = Integer.valueOf(tfchair.getText());
z6 = Integer.valueOf(tfhargachair.getText());
z7 = Integer.valueOf(tfgenset.getText());
z8 = Integer.valueOf(tfhargagenset.getText());
h2 = z1*z2;
h3 = z3*z4;
h4 = z5*z6;
h9 = z7*z8;
btnhitung.setVisible(false);
btnprint.setVisible(true);
int f;
f = h1 + h2 + h3 + h4 + h5 + h6 + h7 + h8 + h9;
tfprice.setText("Rp. " + f + ",00" );
BYE_RECEIPT.cbtenda.setEditable(false);

    }//GEN-LAST:event_btnhitungActionPerformed

    private void cbstageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbstageActionPerformed
        // TODO add your handling code here:
        int pilih;
        String ukuranTenda;
        int hargaTenda = 0;
        pilih = cbstage.getSelectedIndex();
        switch (pilih)
        {
            case 0 :
                ukuranTenda = String.valueOf (cbstage.getSelectedItem());
                hargaTenda = 0;
                break;
            case 1:
                ukuranTenda = String.valueOf(cbstage.getSelectedItem());
                hargaTenda = 1200000;
                break;
            case 2:
                ukuranTenda = String.valueOf(cbstage.getSelectedItem());
                hargaTenda = 2000000;
                break;
            case 3:
                ukuranTenda = String.valueOf(cbstage.getSelectedItem());
                hargaTenda = 4000000;
                break;
            case 4:
                ukuranTenda = String.valueOf(cbstage.getSelectedItem());
                hargaTenda = 7000000;
                break;
        }
        tfhargastage.setText("" + hargaTenda);
        
                
    }//GEN-LAST:event_cbstageActionPerformed

    private void tfhargastageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhargastageActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_tfhargastageActionPerformed

    private void tfhargastandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhargastandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhargastandActionPerformed

    private void tfhargatableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhargatableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhargatableActionPerformed

    private void tfhargalightingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhargalightingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhargalightingActionPerformed

    private void tfhargainstrumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhargainstrumentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhargainstrumentActionPerformed

    private void tfhargachairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhargachairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhargachairActionPerformed

    private void tfhargasoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhargasoundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhargasoundActionPerformed

    private void tfhargacutleryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhargacutleryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhargacutleryActionPerformed

    private void cbstandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbstandActionPerformed
        // TODO add your handling code here:
        int stand = 100000;
        if (cbstand.isSelected())
        {
            tfhargastand.setText("" + cbstand.getText());
            tfhargastand.setText(""+ stand);
             tfstand.setText("1");
        }
        else
        {
            tfhargastand.setText("0");
            tfstand.setText("0");
        }
        tfhargastand.setEditable(false);
    }//GEN-LAST:event_cbstandActionPerformed

    private void cbtableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtableActionPerformed
        // TODO add your handling code here:
        int table = 30000;
        if (cbtable.isSelected())
            
        {
            tfhargatable.setText("" + cbtable.getText());
            tfhargatable.setText(""+ table);
            tftable.setText("1");
        }
        else
        {
            tfhargatable.setText("0");
        }
        tfhargatable.setEditable(false);
    }//GEN-LAST:event_cbtableActionPerformed

    private void tftableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftableActionPerformed

    private void tfstandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfstandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfstandActionPerformed

    private void cbchairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbchairActionPerformed
        // TODO add your handling code here:
        int chair = 15000;
        if (cbchair.isSelected())
        {
            tfhargachair.setText("" + cbchair.getText());
            tfhargachair.setText(""+ chair);
            tfchair.setText("1");
        }
        else
        {
            tfhargachair.setText("0");
        }
        tfhargachair.setEditable(false);
                                  
    }//GEN-LAST:event_cbchairActionPerformed

    private void cbgensetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbgensetActionPerformed
        // TODO add your handling code here:
        int genset = 700000;
        if (cbgenset.isSelected())
        {
            tfhargagenset.setText("" + cbgenset.getText());
            tfhargagenset.setText(""+ genset);
            tfgenset.setText("1");
        }
        else
        {
            tfhargagenset.setText("0");
        }
        {
        
        tfhargagenset.setEditable(false);
    }//GEN-LAST:event_cbgensetActionPerformed
    }
    private void tfhargagensetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhargagensetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhargagensetActionPerformed

    private void tfgensetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfgensetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfgensetActionPerformed

    private void tfchairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfchairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfchairActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        btnprint.setVisible(false);
        String a = tfname.getText();
          String b = tfevent.getText();
          String c = tftanggal.getText();
          String d = tfbulan.getText();
          String e = tftahun.getText();
          String f = tfemail.getText();
          String g = tftelp.getText();
          ComboBoxModel h = cbstage.getModel();
          ComboBoxModel i = cbcultery.getModel();
          ComboBoxModel j = cblighting.getModel();
          ComboBoxModel k = cbsound.getModel();
          ComboBoxModel l = cbinstrument.getModel();
          String m = tfstand.getText();
          String n = tftable.getText();
          String o = tfchair.getText();
          String p = tfgenset.getText();
          String q = tfprice.getText();
        BYE_RECEIPT da = new BYE_RECEIPT();
        da.tacustomer.setText("Name   :"+a+"\n" +"Event's Name :"+b+"\n"+"Event's Date    :"+c+"/"+d+"/"+e+"\n"+
                  "Email   :"+f+"\n"+"Telp/Fax :"+g);
        da.tacustomer.setEditable(false);
        da.taprint.setText("Stand:   "+m+"\n"+"Table :"+"\n"+"Chair :"+o+"\n"+"Genset    :"+p);
        da.taprint.setEditable(false);
        da.cbtenda.setModel(h);
        da.cbtenda.setEnabled(false);
        da.cbalatmakan.setModel(i);
        da.cbalatmakan.setEnabled(false);
        da.cbband.setModel(l);
        da.cbband.setEnabled(false);
        da.cbspeaker.setModel(k);
        da.cbspeaker.setEnabled(false);
        da.cblampu.setModel(j);
        da.cblampu.setEnabled(false);
        da.tfharga.setText(q);
        this.dispose();
        da.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnprintActionPerformed

    private void btncutleryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncutleryActionPerformed
        // TODO add your handling code here:
                JTextArea textArea = new JTextArea(30,10);
  String text = "Basic : \n"
                        + "200 Sets of Cutlery\n"
                        + "\n"
    + "Middle : \n"
                        + "500 Sets of Cutlery\n"
                                + "\n"
    + "Expert : \n"
                        + "800 Sets of Cutlery\n"
                                + "\n"
    + "Exclusive : \n"
                        + "1200 Set of Cutlery\n";
  textArea.setText(text);
  textArea.setEditable(false);
    
  JScrollPane scroll = new JScrollPane(textArea);
    
  JOptionPane.showMessageDialog(null,scroll,"Information Cutlery",JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/Gambar/MovieIcon.png")); 
    
    }//GEN-LAST:event_btncutleryActionPerformed

    private void btnlightingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlightingActionPerformed
        // TODO add your handling code here:                                               
        JTextArea textArea = new JTextArea(30,10);
  String text = "Basic : \n"
                        + "-Par\n"
                        + "-Projector \n"
                        + "-Panel \n"
                                + "\n"
    + "Middle : \n"
                        + "-Par\n"
                        + "-Projector\n"
                        + "-Moving\n"
                        + "-Scanner\n"
                                + "\n"
    + "Expert : \n"
                        + "-Par\n"
                        + "-Projector\n"
                        + "-Moving\n"
                        + "-Pinspot\n"
                        + "-Centerpiece\n"
                                + "\n"
    + "Exclusive : \n"
                        + "-Par\n"
                        + "-Projector\n"
                        + "-Moving\n"
                        + "-Pinspot\n"
                        + "-Centerpiece\n"
                        + "-Followspot\n"
                        + "-Pixel\n"
                        + "-Decorative\n";
  textArea.setText(text);
  textArea.setEditable(false);
    
  JScrollPane scroll = new JScrollPane(textArea);
    
  JOptionPane.showMessageDialog(null,scroll,"Information Lighting",JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/Gambar/MovieIcon.png")); 
    
    }//GEN-LAST:event_btnlightingActionPerformed

    private void btnsoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsoundActionPerformed
        // TODO add your handling code here:
        JTextArea textArea = new JTextArea(30,10);
  String text = "Basic : \n"
                        + "- 1 Speaker, 2 Mic, 1 Soundmixer\n"
                        + "\n"
                        + "Medium : \n"
                        + "- 2 Speaker, 4 Mic, 1 Soundmixer \n"
                        + "\n"
                        + "Expert : \n"
                        + "- 4 Speaker, 6 Mic, 1 Soundmixer \n"
                        + "\n";
                textArea.setText(text);
  textArea.setEditable(false);
    
  JScrollPane scroll = new JScrollPane(textArea);
    
  JOptionPane.showMessageDialog(null,scroll,"Information Sound",JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/Gambar/MovieIcon.png"));
    }//GEN-LAST:event_btnsoundActionPerformed

    private void btninstrumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninstrumentActionPerformed
        // TODO add your handling code here:
                JTextArea textArea = new JTextArea(30,10);
  String text = "Basic : \n"
                        + "- 1 Keyboard, 1 Guitar\n"
                        + "\n"
                        + "Medium : \n"
                        + "- 1 Keyboard, 1 Guitar, 1 Bass, 1 Drum \n"
                        + "\n"
                        + "Expert : \n"
                        + "- 1 Keyboard, 2 Guitar, 1 Bass, 1 Drum, 1 DJ Mixer \n"
                        + "\n";
                textArea.setText(text);
  textArea.setEditable(false);
    
  JScrollPane scroll = new JScrollPane(textArea);
    
  JOptionPane.showMessageDialog(null,scroll,"Information Instrument",JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/Gambar/MovieIcon.png"));
    }//GEN-LAST:event_btninstrumentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BYE_CUSTOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BYE_CUSTOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BYE_CUSTOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BYE_CUSTOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BYE_CUSTOM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btncutlery;
    private javax.swing.JButton btnhitung;
    private javax.swing.JButton btninstrument;
    private javax.swing.JButton btnlighting;
    public static javax.swing.JToggleButton btnprint;
    private javax.swing.JButton btnsound;
    private javax.swing.JLabel bye_music_label;
    private javax.swing.JCheckBox cbchair;
    public static javax.swing.JComboBox cbcultery;
    private javax.swing.JCheckBox cbgenset;
    public static javax.swing.JComboBox cbinstrument;
    public static javax.swing.JComboBox cblighting;
    public static javax.swing.JComboBox cbsound;
    public static javax.swing.JComboBox cbstage;
    private javax.swing.JCheckBox cbstand;
    private javax.swing.JCheckBox cbtable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField tfchair;
    public static javax.swing.JTextField tfgenset;
    public static javax.swing.JTextField tfhargachair;
    public static javax.swing.JTextField tfhargacutlery;
    public static javax.swing.JTextField tfhargagenset;
    public static javax.swing.JTextField tfhargainstrument;
    public static javax.swing.JTextField tfhargalighting;
    public static javax.swing.JTextField tfhargasound;
    public static javax.swing.JTextField tfhargastage;
    public static javax.swing.JTextField tfhargastand;
    public static javax.swing.JTextField tfhargatable;
    private javax.swing.JTextArea tfprice;
    public static javax.swing.JTextField tfstand;
    public static javax.swing.JTextField tftable;
    // End of variables declaration//GEN-END:variables
}
